<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24229" started-at="2019-10-31T20:48:01 IST" finished-at="2019-10-31T20:48:25 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24229" started-at="2019-10-31T20:48:01 IST" finished-at="2019-10-31T20:48:25 IST">
      <class name="com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047@79be0360]" name="setUpBeforeClass" is-config="true" duration-ms="14" started-at="2019-10-31T20:48:01 IST" finished-at="2019-10-31T20:48:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047@79be0360]" name="setUp" is-config="true" duration-ms="12070" started-at="2019-10-31T20:48:01 IST" finished-at="2019-10-31T20:48:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validLoginTest()[pri:0, instance:com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047@79be0360]" name="validLoginTest" duration-ms="11089" started-at="2019-10-31T20:48:13 IST" finished-at="2019-10-31T20:48:24 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [tool100] but found [SQL]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [tool100] but found [SQL]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047.validLoginTest(ELearningAdminCreateCategoryELTC_047.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047@79be0360]" name="tearDown" is-config="true" duration-ms="1001" started-at="2019-10-31T20:48:24 IST" finished-at="2019-10-31T20:48:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.ELearningAdminCreateCategoryELTC_047 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
